name: 'GitHub Java Script'
description: 'Run simple scripts using Java language'
branding:
  color: blue
  icon: code
inputs:
  dependencies:
    description: 'Dependencies for maven'
    required: false
    default: |
      <dependencies> 
      </dependencies>
  java-script:
    description: 'Java script'
    required: false
    default: |
      public static void main(String[] args) {
          System.out.println("Hello world!");
      }
outputs:
  result:
    description: The return value of the java script
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DEPENDENCIES: ${{ inputs.dependencies }}
    JAVA_SCRIPT: ${{ inputs.java-script }}
