name: Run tests on PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: github-java-script
        uses: ./
        with:
          java-script: |
            public static void main(String[] args) {
                System.out.println("Hello world! From PR");
            }
